version: '3.9'

services:
  backend:
    build: ./api
    command: /bin/bash -c "while sleep 1000; do :; done"
    ports:
      - "3000:3000"
    working_dir: /usr/src/api
    volumes:
      - ./api:/usr/src/api
    networks:
      - yummy-network

  frontend:
    build: ./app
    command: /bin/bash -c "while sleep 1000; do :; done"
    ports:
      - "5173:5173"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - backend
    networks:
      - yummy-network

networks:
  yummy-network:
    driver: bridge
    name: yummy-network